[project]
name = "dota2-minify"
version = "1.12.2"
description = "Dota2 Mod Patcher & Toolkit for everyone to use mods easily"
readme = "readme.md"
requires-python = ">=3.13"
dependencies = [
    "dearpygui>=2.1.0",
    "json-with-comments>=1.2.10",
    "playsound3>=3.2.8",
    "psutil>=7.1.0",
    "pyinstaller>=6.16.0",
    "requests>=2.32.5",
    "screeninfo>=0.8.1",
    "vdf>=3.4",
    "vpk>=1.4.0",
]
