name: Cleanup RCs

on:
  workflow_dispatch:

jobs:
  cleanup-prereleases:
    runs-on: ubuntu-latest
    steps:
      - name: Deletion
        uses: jay2610/delete-older-releases@1.0.0
        with:
          repo: ${{ github.repository }}
          keep_latest: 0
          delete_type: "prerelease"
          delete_tag_pattern: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
